server:
  port: 5050
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/**NAME**?enabledTLSProtocols=TLSv1.2
    username: **NAME**
    password: **NAME**
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialize: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  mail:
    from: **NAME**
    host: **NAME**
    port: **NAME**
    protocol: smtp
    username: **NAME**
    password: **NAME**
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
mail:
  smtp:
    starttls:
      enable: false
debug: true

project:
  image: images/

app:
  jwt:
    key: **SECRET_CODE*
    time: 86400000

